image:
  repository: ghcr.io/dgtlmoon/changedetection.io
  tag: ""  # managed by Kargo

replicas: 1

httproute:
  hostnames:
    - changes.dieu.dev

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 50m
    memory: 128Mi
