kube-prometheus-stack:
  grafana:
    enabled: false  # using Grafana Cloud UI with self-hosted Prometheus as external datasource

  prometheus:
    prometheusSpec:
      retention: 30d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: do-block-storage
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi

  alertmanager:
    enabled: false
