kargoAdmin:
  onePasswordItem: kargo.admin

kargo:
  api:
    adminAccount:
      enabled: true
    secret:
      name: kargo-admin-credentials
  argocd:
    integrationEnabled: true
    namespace: argocd
