apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: dieubernetes
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          # Adopt the pre-provisioned load balancer created by Terraform.
          # The LB IP is stable before ArgoCD syncs, enabling DNS to be
          # configured immediately after cluster creation.
          service.beta.kubernetes.io/do-loadbalancer-id: "e80ddc3a-9ee3-447c-b87e-66f897bb1b00"
