apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-otlp-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: grafana-cloud-otlp-credentials
  data:
    - secretKey: password
      remoteRef:
        key: ednzluyjoq2k62kbbeiyqhufti/password
