{{- if .Values.otlpAuth.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.otlpAuth.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: {{ .Values.otlpAuth.secretName }}
  data:
    - secretKey: authorization
      remoteRef:
        key: {{ .Values.otlpAuth.onePasswordItem }}/authorization
{{- end }}
