image:
  repository: ghcr.io/mealie-recipes/mealie
  tag: ""  # managed by Kargo

replicas: 1

env:
  ALLOW_SIGNUP: "false"
  BASE_URL: "https://recipes.dieu.dev"
  DB_ENGINE: sqlite

httproute:
  hostnames:
    - recipes.dieu.dev

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
