{{- if .Values.otlpIngest.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-otlp-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: loki-otlp-auth
  data:
    - secretKey: htpasswd
      remoteRef:
        key: {{ .Values.otlpIngest.onePasswordItem }}/htpasswd
    - secretKey: authorization
      remoteRef:
        key: {{ .Values.otlpIngest.onePasswordItem }}/authorization
{{- end }}
