apiVersion: v2
name: envoy-gateway
description: Envoy Gateway — cloud-agnostic Gateway API implementation
version: 0.1.0
dependencies:
  - name: gateway-helm
    version: "1.8.1"
    repository: https://gateway.envoyproxy.io/helm
