apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-admin-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: kargo-admin-credentials
  data:
    - secretKey: ADMIN_ACCOUNT_PASSWORD_HASH
      remoteRef:
        key: fhygr5davlgoiugn3oggxovcte/password_hash
    - secretKey: ADMIN_ACCOUNT_TOKEN_SIGNING_KEY
      remoteRef:
        key: fhygr5davlgoiugn3oggxovcte/token_signing_key
